dist: trusty
addons:
  chrome: stable
sudo: required
language: java
jdk:
- openjdk8
env:
  global:
  - TERM=dumb
  - MALLOC_ARENA_MAX=1
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=372m -XX:+CMSClassUnloadingEnabled"
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: W08aMUtRD+SUWY0Xe4t9Jhv+uVS3CDSpQuNn63fylR0bCKBnRI8TJWzSm5oTWH1EuIrFP9H8D0lY7UlzzNaemwFPOZ+YXmNnYqTlJ1P6eRyIGSQ6TpS1wJsMx0EzTeeTx+TpPQ4cmcvQlHQC9ZJS7knAP2/k6IY9cbuo90JHXgmPHAwWvIOwJvHo5dqPCyhqLkWvkEtQmywe73C/e921uLgE120que7nzq5z+njad7FNa1Kr36eYjMwjUybouE2tEOgQ0bEBhM6cJDPI1EKN0n9cnJs98rhLRFY00b7OUKl1HmGOl6RB8WW4OuJu6JNsrSJBl3019yamnmpkK4sI+O3ZEicS1z2iG7w1gSjG8rYr1srhBdxHCHJzx9Kw9pdJCOaTVyQvCdXTjbdEjMeMI1BvhUdY5zkWlasiWGBBif8QwaeUsyj+Hh9nE6OZQQ/gywrqVzLJ8SsHKx3jJ0O6e5kZwwllvo74e05SIQg2Coe/bS60jzKvG0jak///GGRWnIOHeumofqwywUzP4uJle6xWYzpheJNbN/w92jaAJovsg9o87AixS/sJ8zvLmrx42uBQHudDytSxQZCzVxW2UQZXknB/omTzEWPy1PaxwyLsQEutE5npvXETNnOVu/ynEyLQb1wPHCfzmi+nN4vxcukXPU0tdAujySa2TDtB6wQ=
  - secure: fSlvGAWevCRxefJG6im2rZ3B4B3xfNnOQ/8QlEbLoBVxvAuhJkojeo0E4ITXrXw0kajfFYEDbJHml2ROMNeBivzAsFov6mjAYkWD29l1/SxcDOSNegcRy6PkKADbBHDmifklC04RJIBeT/K/AoripSXDirZkiQeLfwvERc/j9iFAcw8wW7oEeKec8duOAjHRSZIFhUIUV5lkGwtNVCTL4bKytu2UbTnVvB6hwPr2eFI+8gnz7nslMU0NzHc9Z7Hh8ztH5Xun5soy6La+jX/LQeJuCuWppAM35W44Sx6jbaqFywjcUJ4RP/xWtrHe6IouNGdD2+KYzHAEIwuPjuUdzwCVzIBfqtoaCyykNbKkDn/6L8H+SVSWFYzogwBE3n04E0Mz5xYdtAu6tjeGWC/CUyXcpSgDRRyA8wSme8bQUAIpO0JjexOeOfXHaBJy9jrUNcXBp6F8POxuayU4MdCmunWj5Aw7thw8ZO0GzA1I+3AOlBk2qaQihht9Mb1/xA8UgwLPhMqJFOzwsd8UzOqvy76Qq23iVcVgh0ARY8Rcl0T82dvonj/B/755wJuGalia5epfjjS6o8hs0KNnb6aMDohqYpDquUCqIyQQL/dj9kzGkBRQHBZAfzrdYTjOZvfncpFgcuRlzl5cbtZWJwZNrww+vQ1gH2SmMP2qsRTy78Y=
  - secure: YHltZT0MNrgZoYEdiqiECAlOq3Q0ggrukDt4tb24Q1O+PU7yW43+653dN1pmiMTDU4tDZmSBoD7aKRq2yl5Q5l41mO5rTn8QEPykC0B8HGOu7vZZFY6FlxSZvqlLifyi5bdtaZdwicnlOQVzrC1WyUI0YCFjKQZAbXVN5xEIYIpcAqB0ndj1VGdHJxSR3tjIYtzqtmUB57XhsKLCt6FhSXn6BO6OEsfz8PY3zCVvOh5y1kez7nY8PxGYXtb7rdUgUSBgSPND60P+vFhGFEBXTJFldecp1A1euaEeyIkyAG+Qx1dHcOPSBX6nkufXsJm1lin4t0pDiJSHzeNAJwuuYYArMQn24RYlOYsIgfzf5/fXtUx5VtjXvyYjiz1mKKRnXTKF8Irj1hCklaLvg6pcn0qFn9H3tUKB0DL9iouXmQOBqMKFK5CsuDFf8N/R4Um0Qh8FwvaNj6ctsMIPrqRHyHUxu5ASslQMqgu+reOPlP/iViHdgRTotEstk7vQF53KBA9MJUJtKft4x/EPijUhu9Z8gz1f+bHEUycK2reIAwJXp2c/HunVFGZrapxoF2YddV700onVzXsSUP7eWMyZ/vFm2XTfOCe1oO54/qyV/j5zUWcrWWGx8FikkaPFhVC54n9+kVtjmFR0i5KpxUnAtGB8pExsq5Mj157iFFi09zE=
install: "/bin/true"
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis-build-pr.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis-build.sh; fi
cache:
  directories:
  - "$HOME/.gradle"
deploy:
  provider: releases
  api_key:
    secure: WHH8c5d6dGOmU4T5EUu1uWlmUqtbe5h6o9DNXRQYQe1v8+ep/igYoB0zxCtL0o7wtrN/l1T1+evHEYMpeylYAlyDxmH1sFgMn+ZQNbELcHOzhdErdOlp97/ZRGOW58haWWp3md+UjM9Z4jZBw2/1coxJUYioLBB5WZuzYxsq8hGVyZYqFObY8pKlc4ncTKsfRFeUgKOtIB5EWda8vXSkd9ocxVvxxtyN9UVPeQQ+mi5d/6pQPI0zRii9DUQ77lncV3LVS5vtr+1M2OGSK4FdQuWt6eToPTJCK9NfB3CZOwlgEucpfLy8pcJLtxZp4gIzAW2/5WtG6u52TbdUvgNAcDtU0o98z6zs7vUuS/ef7L7QKnm6VzbYbwYDSUePDxlXtdTAYj+7AaMgAyEofDhm/Yi7aLsVXDcNeXb5naB17Fe6GFPW2dg6tCVcpYwOJRwH0TQRdd7ZMLwZoSIUT1v2zWTjyLjCSmvrvQIBgJOue8bSES2JFKIbGUQqOj/VrJIF2AbH0wdn9cALEy21qeRuB1lqTKBpb2lLjeHfxhWAXkKXHiGCNbXbo3eC6HDMoe6Fd17ehxWr3cPx5I0RTZQrkQD+mX/xiYM3FAxPIhyrdAibTjhqSgCN5hccHLLFVB0K8arKmhAmW6HkuSKZx1KWKyIhMKwF2UqEKJbSVYqr2qU=
  file: cli/build/distributions/micronaut-${TRAVIS_TAG:1}.zip
  on:
    repo: micronaut-projects/micronaut-core
    tags: true
    all_branches: true
